# Generated by Django 5.0.6 on 2024-07-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_rename_blog_comment_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('view', 'view'), ('hidden', 'hidden')], default='view', max_length=10),
        ),
    ]
